#!/bin/bash

export BASEROW_IMAGE_VERSION=1.26.1
export CLT_REQUIREMENTS_VERSION=1.7
export CLT_VERSION=11.3.2
export BASE_BASEROW_CLT_IMAGE_VARIANT=d
export COMBINED_BASE_VERSION=${BASEROW_IMAGE_VERSION}-${CLT_VERSION}-${BASE_BASEROW_CLT_IMAGE_VARIANT}
export BASE_BASEROW_CLT_IMAGE=lucwastiaux/baserow-clt:${COMBINED_BASE_VERSION}