# Generated by Django 3.2.13 on 2022-09-04 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0084_duplicatetablejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.field')),
                ('language', models.CharField(blank=True, default='', help_text='Language', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('database.field',),
        ),
        migrations.CreateModel(
            name='TransliterationField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.field')),
                ('transliteration_id', models.CharField(blank=True, default='', help_text='Transliteration key for this service', max_length=2048)),
                ('source_field', models.ForeignKey(blank=True, help_text='The field to transliterate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='baserow_vocabai_plugin.languagefield')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.field',),
        ),
        migrations.CreateModel(
            name='TranslationField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.field')),
                ('target_language', models.CharField(blank=True, default='', help_text='Target Language', max_length=255)),
                ('service', models.CharField(blank=True, default='', help_text='Translation Service', max_length=255)),
                ('source_field', models.ForeignKey(blank=True, help_text='The field to translate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='baserow_vocabai_plugin.languagefield')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.field',),
        ),
        migrations.CreateModel(
            name='DictionaryLookupField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.field')),
                ('lookup_id', models.CharField(blank=True, default='', help_text='Dictionary lookup key for this service', max_length=2048)),
                ('source_field', models.ForeignKey(blank=True, help_text='The field to do dictionary lookup for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='baserow_vocabai_plugin.languagefield')),
            ],
            options={
                'abstract': False,
            },
            bases=('database.field',),
        ),
    ]
