# Generated by Django 3.2.13 on 2022-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baserow_vocabai_plugin', '0002_auto_20220914_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabAiLanguageData',
            fields=[
                ('record_key', models.CharField(default='language_record', max_length=100, primary_key=True, serialize=False)),
                ('language_list', models.JSONField()),
                ('free_transformation_options', models.JSONField()),
                ('premium_transformation_options', models.JSONField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
